### ISSUE TITLE
PD Diagram on Page 003 Is cropped at bottom

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/sotc-2015#1]
Note bottom of date text.

![cropped-pd-diagram-p3](https://cloud.githubusercontent.com/assets/21746/11577523/04733e64-99d3-11e5-9e62-545dc9ff4b7c.png)

Chromium Version 46.0.2490.71 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

**Comment by mattl** [comment]
Are you referring to that little break in the image?

**Comment by rheaplex** [comment]
No, although that too.

Look at the "2006" label, the bottoms of the 0s are clipped compared to the top, and the 6 almost has a gap in it at the bottom (perceptually). I think the SVG bounding box is slightly too small there.

**Comment by mattl** [comment]
Fixed.
