### ISSUE TITLE
gap between grey bar and top of page

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#103]
see

![gap](https://cloud.githubusercontent.com/assets/6394777/11647747/e986f11c-9d20-11e5-9f09-40050dea7b34.jpg)

**Comment by mattl** [comment]
Yeah, intentional

**Comment by janetpkr** [comment]
It looks really bad on the web though, especially if this is what people land on first? see attached
![gap2](https://cloud.githubusercontent.com/assets/6394777/11647973/7d1285ac-9d23-11e5-8644-b1bb60f80b01.jpg)

**Comment by mattl** [comment]
Maybe I'll lose the grey background? Running out of time.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
