### ISSUE TITLE
fix html formatting for one of the social media links on cultural heritage section

### ISSUE THREAD

**Issue by tvol** [creativecommons/sotc-2015#106]
stateof.creativecommons.org%2F2015%2Fcc-sotc-2015-xx10.html&via=creativecommons“>

**Comment by mattl** [comment]
What's not working?

**Comment by tvol** [comment]
in chrome and safari there's that link above spelled out instead of linked to an image, i think

**Comment by mattl** [comment]
screenshot?

**Comment by tvol** [comment]
![screen shot 2015-12-08 at 10 16 29 am](https://cloud.githubusercontent.com/assets/231665/11664132/d00b798c-9d94-11e5-8ef5-c465ba6097c6.png)
