### ISSUE TITLE
DE translation: 139 vs. 136 vs. actually 247 dots meaning Billions

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/sotc-2015#112]
the dot matrix about "139 Billion views" (in the EN version it's 136 Billion) says 1 dot = 1 Billion, but features roughly 247 dots. Wouldn't that mean there were 247 Billion views?

**Comment by mattl** [comment]
I think the dots are just a representation, not literal.

**Comment by rebeccakross** [comment]
It's literal. Text should say 136 billion and there should be 136 dots.
