### ISSUE TITLE
DE translation: Open Ed flags

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/sotc-2015#115]
the flags hailing "OPEN EDUCATION" in EN don't hail anything in the DE translation

**Comment by mattl** [comment]
It seems you didn't translate "Open Education" on the form.

**Comment by RCEurope1** [comment]
German translation of Open Education is something nobody can want, so should stay Open Education

**Comment by mattl** [comment]
I'm confused. Is this even an issue?
