### ISSUE TITLE
Missing notes and data sources

### ISSUE THREAD

**Issue by ilabastida** [creativecommons/sotc-2015#125]
In the original report there are notes at the bottom of any graph or table, it might be interesting to translate them in order to understand the figures. It makes a lot of sense especially when we mention the different languages of the deed and there is a sign on some of them that do not point to anywhere in the translations (see for instance french, german or english)

**Comment by janetpkr** [comment]
This wasn't in the condensed version of the report. 

They are in the full version of the report, which I've created a google form for translation and is awaiting @mattl's review before we send out to affiliates interested in translating the full version.
