### ISSUE TITLE
missing strings from platforms data

### ISSUE THREAD

**Issue by ilabastida** [creativecommons/sotc-2015#126]
There are some strings not available for translation in the data from platforms, 500px or Wikimedia Commons. In the data from PLOS there is an asterisk in the original one that it is not shown in the translations. moreover in the corresponding not there are extra ()

**Comment by janetpkr** [comment]
Can you specify which strings? I'm not sure what your'e talking about. If any of them are in graphics, those are not being translated. If any of them are in charts, @mattl added those for web version which is why they are not in the condensed version for translation strings.

**Comment by ilabastida** [comment]
This table:

Platform    Number of works in the commons
Flickr  356 million photos
Bandcamp    1.95 million tracks
Wikipedia   35.9 million articles
....

..has those lines untranslated (there are not the corresponding strings to translate)

500px   661,000 photos
...
Wikimedia Commons   21.6 million media files
...
Boundless   49,000 open educational resources

**Comment by janetpkr** [comment]
@ilabastida They are not missing. They are already accounted for with the generic __ million tracks strings that were supposed to be in the images for the condensed version. @mattl should have what he needs now to update the chart (which is only extant in the web version but is the same text as the platform images).

@mattl moving over to you now.

**Comment by gyg3** [comment]
Gh

**Comment by gyg3** [comment]
Gh
