### ISSUE TITLE
Include all Wikimedia projects

### ISSUE THREAD

**Issue by nemobis** [creativecommons/sotc-2015#132]
I don't understand https://stateof.creativecommons.org/2015/data.html#cc-is-everywhere-millions-of-websites-use-cc-licenses-including-major-platforms-like-wikipedia-and-flickr-and-smaller-websites-like-your-grandmas-blog : why are only Wikipedia and Commons included?

Wikimedia projects are much more: https://meta.wikimedia.org/wiki/Wikimedia_projects
The grand total is currently about 81 millions: https://meta.wikimedia.org/wiki/List_of_Wikimedia_projects_by_size#footer (some of those cc-by-sa works embed PD works, e.g. on Wikisource).

There are also 15 millions CC0 items on Wikidata: https://www.wikidata.org/wiki/Special:Statistics

**Comment by mattl** [comment]
This is a good suggestion for next year's report. Please make an issue at https://github.com/creativecommons/sotc-2016/issues and it can be considered for inclusion in the next report.
