### ISSUE TITLE
Use MediaWiki Translate

### ISSUE THREAD

**Issue by nemobis** [creativecommons/sotc-2015#134]
I'd like to add an Italian translation but I can't understand the instructions at https://github.com/creativecommons/sotc-2015#translations .

Can you please use the [Translate extension](https://www.mediawiki.org/wiki/Help:Extension:Translate), which is much easier? You could for instance install it on [wiki.creativecommons.org](https://wiki.creativecommons.org/wiki/Special:Version) using the [MLEB](https://www.mediawiki.org/wiki/MLEB) tarball and add your strings with a message group pointed to this repository.

**Comment by mattl** [comment]
This is a good suggestion for next year's report. Please make an issue at https://github.com/creativecommons/sotc-2016/issues and it can be considered for inclusion in the next report.
