### ISSUE TITLE
pg 1 - nix the chart under the graph

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#14]
It's incorrect and doesn't exist in the original report.

**Comment by mattl** [comment]
we can update it. but this is the web, we need to provide a reasonable alternative to looking at a very small chart on a tiny screen (assuming you can see the chart at all, which is a dangerous assumption)

**Comment by janetpkr** [comment]
We provide the data in data sources. This is the design of the report that people see. If people want the raw data they can go to data section.

**Comment by mattl** [comment]
The charts are too small, and inaccessible. Removing the tables would be doing a disservice to people.

**Comment by janetpkr** [comment]
please update chart to these numbers then:

2006: 140 million
2010: 400 million
2014: 882 million
2015: 1.1 billion

**Comment by janetpkr** [comment]
This is not updated.
