### ISSUE TITLE
Suggestion: Mark current page at bottom

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/sotc-2015#2]
Highlighting, bolding, underlining or otherwise marking the current page number at the bottom of the page would make navigation much easier, especially on systems without the url containing the page number readily displayed at the top of the window/screen.

**Comment by mattl** [comment]
Nav is very temporary. We're going to have nice nav that tells you what the next page is.

**Comment by janetpkr** [comment]
What about a all-in-one-page version like last year? Easier to scroll through.

**Comment by mattl** [comment]
not built for that. Built like this for the ability to link to particular pages.
