### ISSUE TITLE
p3 - "NO. OF MARKS CC0 + PDM" should be bolded

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#21]

**Comment by mattl** [comment]
It is.

**Comment by janetpkr** [comment]
see attached 
![unboldedp3](https://cloud.githubusercontent.com/assets/6394777/11578816/814cb2e4-99dd-11e5-8d6a-d99cf310d553.jpg)

desktop
chromium Version 45.0.2454.99 (64-bit)

**Comment by mattl** [comment]
That's bolded in the font we have, I had to make them all the same because the "light" text isn't readable on a small screen (or even very readable on desktop) at small screen sizes.

**Comment by janetpkr** [comment]
Ok, if there's no way to make the no. of marks more bold i guess it's not a huge deal
