### ISSUE TITLE
p6 - font in bubbles needs to be changed to be like the rest

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#27]
times new roman? preposterous!

**Comment by mattl** [comment]
screenshot please

**Comment by janetpkr** [comment]
![font in bubbles](https://cloud.githubusercontent.com/assets/6394777/11579363/52e19456-99e2-11e5-8f70-d253af003168.jpg)

**Comment by janetpkr** [comment]
same for onepage
