### ISSUE TITLE
p7 - font is too light and missing box

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#31]
see attached

chromium Version 45.0.2454.99 (64-bit)
![platforms graphic](https://cloud.githubusercontent.com/assets/6394777/11578395/e8566182-99d9-11e5-8842-0172b060c55a.jpg)

**Comment by mattl** [comment]
the font is the same as the design. the font is too light in general, and that's the reason for a number of bold text changes. 

again, i implore you to look at this on a mobile device. things like the images and box are unreadable on mobile, which is the reason for having tables and alternative captions in place.

**Comment by janetpkr** [comment]
Can we bold the text then? A lot of people will be reading this on the web, not on mobile, so we need it to look good on web too.

**Comment by mattl** [comment]
yep, we can. we should probably bold all the light text.

do you agree?

**Comment by janetpkr** [comment]
on this page for the platforms yes. not for the other pages across the board i don't think. should be case by case.
