### ISSUE TITLE
p8 - textbook graphic shows times new roman font

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#39]
see attached
![textbook text](https://cloud.githubusercontent.com/assets/6394777/11578497/0adfb9d2-99db-11e5-82d0-f7f2410ab466.jpg)

chromium Version 45.0.2454.99 (64-bit)

**Comment by mattl** [comment]
Check again.

**Comment by janetpkr** [comment]
Now the graphics on that page are gone 
![textbookgraphicgone](https://cloud.githubusercontent.com/assets/6394777/11578920/4ede00be-99de-11e5-8d56-8dac4227c4df.jpg)

desktop chromium Version 45.0.2454.99 (64-bit)

**Comment by janetpkr** [comment]
no longer times new roman but now is too light. should bold to emphasize. same for onepage.

see 
![textbooktext](https://cloud.githubusercontent.com/assets/6394777/11599369/5b1a3350-9a7b-11e5-9785-4e83ada0f99d.jpg)
