### ISSUE TITLE
Logos on Page 009 Are Outlined in Light Grey

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/sotc-2015#4]
Is this intentional?

![image](https://cloud.githubusercontent.com/assets/21746/11577564/794c5644-99d3-11e5-816e-58980cffc8c3.png)

**Comment by mattl** [comment]
Yeah, I thought it looked nice. Especially as they're a bit... floaty on mobile.

**Comment by janetpkr** [comment]
I think they shouldn't be outlined in grey -- should be according to design.

**Comment by rheaplex** [comment]
@mattl I do see what you mean about floaty.

Can they be centred vertically in rows? That might address that.
