### ISSUE TITLE
p10 - bassel text should be bolded

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#49]

**Comment by janetpkr** [comment]
same for onepage

**Comment by mattl** [comment]
which text?

**Comment by janetpkr** [comment]
#FREEBASSEL: Lead of Creative Commons Syria, Bassel Khartabil is a key contributor to projects that digitize, preserve, and share cultural heritage. He has been illegally imprisoned in Syria since March 2012. CC and its Board of Directors continue to call for Bassel’s immediate and safe release.
