### ISSUE TITLE
Suggestion: one scrolling report with option to view page by page

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/sotc-2015#5]
cumbersome right now to view / click / view / click / view / click when I want to be able to do a high level scan of the full report and then dig into the pieces that interest me.

**Comment by mattl** [comment]
That's not really possible.

**Comment by janetpkr** [comment]
If this is not possible, we need to have a link at the top to a PDF version of the report that does this.

**Comment by rebeccakross** [comment]
Too much to ask people to click 14 times in a report that they don't know where their specific interest will be. We need a high level scanning option. It's what 90%ish of our readers will be doing.

**Comment by mattl** [comment]
Yeah, we'll have a PDF for sure.

**Comment by rebeccakross** [comment]
Default viewing option needs to be the full report in either PDF or web.

**Comment by janetpkr** [comment]
Why isn't this possible Matt? Can you elaborate?

**Comment by mattl** [comment]
Please report bugs, instead of making fundamental design changes at this point.

**Comment by ryanmerkley** [comment]
I'd like to hear the answer to Jane's question please. It's a usability
question.

**Comment by mattl** [comment]
I have a 13 page PDF and 13 pages of SVG to work from. We have a 13 page site, and one that works well on mobile devices.

If that's really going to change now, I will have a fair chunk of work to make it different. I do intend to make the navigation better.

**Comment by ryanmerkley** [comment]
I imagined it would just be a continuous scroll like last time. This is how
the Tumblr generation does it.

R.

**Comment by mattl** [comment]
Yeah, I don't think that'll be possible in the time we have.
