### ISSUE TITLE
p13 circles have turned into blocks with bullets

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#54]
see attached. Also CC BY license icons are missing!
![lastpage](https://cloud.githubusercontent.com/assets/6394777/11578758/25582360-99dd-11e5-8225-ceb74e2aec80.jpg)

desktop
chromium Version 45.0.2454.99 (64-bit)

**Comment by mattl** [comment]
Yeah, we can't do the circles in any meaningful way with the links still being useful.

CC-BY icons are another issue.
