### ISSUE TITLE
onepage - page width

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#59]
I understand this has to be adjusted for mobile, but it doesn't look good to land on the expanded length from the get-go. Is it possible to have a width version that is set like we did for last year's SOTC, see https://stateof.creativecommons.org/report/. And then we could have a link to "view it on mobile" for the width that expands and contracts according to screen. 

I think the primary landing should be made for web, not mobile.

**Comment by mattl** [comment]
There's no "mobile" version. It's a single report, built for the web, regardless of screen size.
