### ISSUE TITLE
Main SOTC header graphic

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/sotc-2015#6]
Needs to be as is in design P1. Key to our design, and key to graphics that will be used throughout YE campaign.

**Comment by mattl** [comment]
Can't do it in a way that works responsively.

**Comment by rebeccakross** [comment]
We'll need to figure out a compromise. Can you make some suggestions?

**Comment by mattl** [comment]
Bear in mind that this is a website, and needs to work well on super tiny
screens and big monitors, so headers will be slightly different on the web,
as they're blocks of text with a background, and not everything is possible
in that format without a bunch of workarounds that may break things further
especially with the limited amount of time we have.

**Comment by rebeccakross** [comment]
Draft graphics were submitted weeks ago to ensure they could move into web easily. Nothing was flagged at that time. I'm just asking for the header and closer graphics please, not throughout, and just some kind of improved treatment, if perfect isn't possible.

**Comment by janetpkr** [comment]
Agree that draft headers for all the sections should be the way they were originally designed. If we make them images, will it work?

**Comment by mattl** [comment]
The images look really bad to the point of being unreadable on mobile.
