### ISSUE TITLE
onepage - header text should be bolded

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#68]
or text that is part of image (however it's formatted) see attached
![headertext](https://cloud.githubusercontent.com/assets/6394777/11598316/0a1fb6be-9a76-11e5-8a61-741396f8afe6.jpg)

**Comment by janetpkr** [comment]
Now it's a little too bold! Sorry to be a pain in the ass, but is there a happy medium? See 
![Uploading boldtext.jpg…]()

**Comment by mattl** [comment]
Found a happy compromise I hope. It does mean individually stroking each word, so it's not something we can do a lot of for time reasons.
