### ISSUE TITLE
onepage - hewlett logo misleading

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#78]
I know @ryanmerkley wanted this left in the report, but page is misleading b/c hewlett adopted CC policy before 2015. NBD?

**Comment by ryanmerkley** [comment]
I don't feel strongly about it being left in -- my main feedback was that it was awkwardly positioned in the original layout. It would be nice to include them. Also the later point references an amount of funding $1.9B that includes their grant pool.

**Comment by ryanmerkley** [comment]
If it's assigned to me, I'd say leave it in for the above reasons.
