### ISSUE TITLE
Page 007 - Grandma's Blog

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/sotc-2015#8]
"smaller websites like your grandma’s blog"

This looks like the "easy enough for your grandma to use" antipattern, although if one's grandmother has a blog they are clearly tech literate. One to evaluate and either change or be prepared for people to remark upon.

**Comment by mattl** [comment]
Yeah, I don't like this either. @rebeccalendl

**Comment by ryanmerkley** [comment]
Confession: me neither.

**Comment by mattl** [comment]
:+1: let's fix it.

**Comment by ryanmerkley** [comment]
Content belongs to Jane/Rebecca. For process integrity, I'd like their sign
off.

**Comment by janetpkr** [comment]
you guys! everyone had a chance to comment on final text multiple times BEFORE it was sent to designer. also this is the version that is being translated. I would suggest just to keep it unless you want the English version being different from all the rest.

@rebeccalendl

**Comment by mattl** [comment]
Would be nice to fix this.

**Comment by rebeccakross** [comment]
Copy has been finalized and approved across all staff and affiliates after multiple rounds of review. Don't feel like we can make unilateral changes at this stage.
