### ISSUE TITLE
Onepage - Link to dif report versions, social media, and list at top

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#84]
For the canonical stateof.cc.org url, which will host the onepage, add links to 
- PDF version
- data section
- tweet sharing the report
- fb sharing the report
- cc mailing list sign-up

Like we have on 2015 stateof - see attached

![sotc top buttons](https://cloud.githubusercontent.com/assets/6394777/11634276/740e5f6c-9cc4-11e5-869f-0faef724545a.jpg)

**Comment by janetpkr** [comment]
copying @rebeccalendl in case there's anything else we should include

**Comment by mattl** [comment]
not linking data here, as its linked throughout and in the footer.
