### ISSUE TITLE
Calling out sections for tweeting like 2015 report?

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#85]
Should we do this, and if so, which ones? 

See last year's https://stateof.creativecommons.org/. 

copying @mattl to see if it's possible or only enough time to focus on other remaining sotc issues and translations at this point.

**Comment by mattl** [comment]
Yeah, this was the intention with the pages of the report.

**Comment by janetpkr** [comment]
Cool, let me know if you need anything from me for it. The headers for those pages should be sufficient for the tweet

**Comment by rebeccakross** [comment]
And include infographic too when possible

**Comment by rebeccakross** [comment]
These aren't showing up for me (https://aboutmybrowser.com/RumGurq6).

**Comment by mattl** [comment]
You may be checking an old page. Are you looking at the live site?

**Comment by rebeccakross** [comment]
Ah nevermind I see them tucked now into each page. Looks like the infographics aren't being pulled into the tweet / post though.

**Comment by mattl** [comment]
Do you have example tweets where they didn't work?

**Comment by janetpkr** [comment]
All of them. 

See 
![tweetinfographicnone](https://cloud.githubusercontent.com/assets/6394777/11648949/137f43ae-9d2e-11e5-8c14-cd814c8ea3f3.jpg)

![fbinfographicnone](https://cloud.githubusercontent.com/assets/6394777/11648952/1af009fc-9d2e-11e5-8344-31ce496f2f25.jpg)

**Comment by mattl** [comment]
Until you post I don't believe it shows the image, certainly not until the
first time someone posts it in a fixed period.

**Comment by janetpkr** [comment]
Hm, ok. Well I don't want to test that until tomorrow! What do you think
@rebeccalendl? Take our chances and hope it works.

On Mon, Dec 7, 2015 at 10:06 PM, Matt Lee notifications@github.com wrote:

> Until you post I don't believe it shows the image, certainly not until the
> first time someone posts it in a fixed period.
> On Dec 8, 2015 12:01 AM, "Jane" notifications@github.com wrote:
> 
> > All of them.
> > 
> > See
> > [image: tweetinfographicnone]
> > <
> > https://cloud.githubusercontent.com/assets/6394777/11648949/137f43ae-9d2e-11e5-8c14-cd814c8ea3f3.jpg
> > 
> > [image: fbinfographicnone]
> > <
> > https://cloud.githubusercontent.com/assets/6394777/11648952/1af009fc-9d2e-11e5-8344-31ce496f2f25.jpg
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/creativecommons/sotc-2015/issues/85#issuecomment-162778681
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/sotc-2015/issues/85#issuecomment-162780082
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by rebeccakross** [comment]
Def don't want to send anything out! Unless there's a way to test internally, we gotta take our chances.

**Comment by mattl** [comment]
If it doesn't work, it'll be easy to fix. I'm confident it works.
