### ISSUE TITLE
Add links to appropriate data section in report

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#86]
Once data section is up with headers, should be obvious which section should be linked to every time in report it says:

"Dig into our [data sources]"

**Comment by mattl** [comment]
Once I'm done, I'll share all the files with you and you'll be able to add links in the Markdown.

**Comment by mattl** [comment]
Actually, I'll just make this a bit easier. @janeatcc Give me the anchor names for each of the links in the document, in order and I'll get them in now.

**Comment by janetpkr** [comment]
#more-than-1-billion-cc-licensed-works-in-the-commons-as-of-2015
#more-people-are-choosing-to-share-openly
#the-public-domain-is-growing
#in-2015-cc-licensed-works-were-viewed-online-136-billion-times
#to-date-the-4.0-license-suite-has-been-officially-translated-into-7-languages-with-3-more-to-be-published-before-the-new-year.
#from-research-to-cute-cat-photos-the-commons-offers-a-treasure-trove-of-content.
#cc-is-everywhere-millions-of-websites-use-cc-licenses-including-major-platforms-like-wikipedia-and-flickr-and-smaller-websites-like-your-grandmas-blog.
#countries-with-open-education-policies

lastly, for "Data, Notes and Acknowledgments." at end:
link to beginning

**Comment by mattl** [comment]
Awesome. thanks Jane.

I put in placeholder links that don't go anywhere right now.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
