### ISSUE TITLE
nested lists show up on github but not data.html

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#88]
See data.html and Boundless (#boundless-49000-open-educational-resources) for example. The "geographic breakdown" doesn't show the list nested under it.

**Comment by mattl** [comment]
You'll need four spaces, rather than two, and also change \* to - for the nested list. Seems Pandoc is a little stricter than GitHub's Markdown implementation.

**Comment by janetpkr** [comment]
So to be clear, example:
- Exact total: 661,307
  - CC BY-NC: 114,024

Look good?

**Comment by mattl** [comment]
Yep.

**Comment by janetpkr** [comment]
updated in github, waiting for data.html refresh to make sure it reflects before closing
