### ISSUE TITLE
Page 007 - platforms.png is blurred on Laptop Screen

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/sotc-2015#9]
Logos are blurred, text is pale and blocky.

Lenovo T440s, Chromium Version 46.0.2490.71 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit) .

![image](https://cloud.githubusercontent.com/assets/21746/11577738/03965826-99d5-11e5-9e8d-40044c5ecdf6.png)

**Comment by mattl** [comment]
Still the case?

**Comment by janetpkr** [comment]
Not for me. @robmyers ?

**Comment by rheaplex** [comment]
Crisp and clear.

Thanks!
