### ISSUE TITLE
PR folks want a media contact posted at bottom of stateof

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#90]
I think better to have a link to the press release which will have contact info for Ryan and I.

Please add to bottom below "Data, sources, scripts and editable images for the entire report can be downloaded at https://github.com/creativecommons/sotc-2015" after another <hr> line:

Media: For report contacts see the Press Release(link to http://creativecommons.org/weblog/entry/46632 - which will be live tomorrow)

**Comment by ryanmerkley** [comment]
I do not want my email or phone # on a public page/release pls.

**Comment by janetpkr** [comment]
Me either. Then let's just nix it.

**Comment by janetpkr** [comment]
Actually let's add this text instead:

<hr>

Media contact: press@creativecommons.org

**Comment by janetpkr** [comment]
Please add at bottom of one page:

<hr>

Media contact: marci@zincstrategies.com
