### ISSUE TITLE
dutch translation - missing strings

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2015#98]
STATE OF THE COMMONS
Impact 2015: CC + Foundation Open Policy

**Comment by mattl** [comment]
I can show you where these go in data files, later.

**Comment by mzeinstra** [comment]
They are not missing, they are the same in Dutch..

State of the Commons is the name, we decided not to translate. 
Impact is impact in Dutch
Foundation Open Policy is again a name that we decided not to translate.
